# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e668a36aa742d66c4d89ef960e66eda6b553ba6693718953a4a7100d1f05e2683be3e514dc6320004a182c00ddb55606ad94da091f2a727f2689fac9a3f78d89

test:
  secret_key_base: 6cea7613761febc64316f7d1ac588068038b390be12d0183735917a4f9e13b7a7949af8e209cbb891ef907c0da5e7b60a259b44b2bf0e6a7d0f0cdfd04568bc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
